In [1]:
import pandas as pd
import numpy as np

In [2]:


np.random.seed(42) #Supaya Hasilnya Sama Semua

n = 100
data = pd.DataFrame({
    'id_transaksi': range(1, n+1),
    'nama': np.random.choice(['Budi', 'Ani', 'Citra', 'Doni', 'Eka'], n),
    'umur': np.random.randint(18, 60, n).astype(float),
    'kota': np.random.choice(['sby', ' SBY', 'Surabaya ', 'jkt', 'Jakarta'], n),
    'jenis_pembayaran': np.random.choice(['Transfer', 'CASH', 'QRIS', 'transfer'], n),
    'total_belanja': np.random.randint(50000, 2000000, n).astype(float),
    'tanggal': pd.date_range('2025-09-01', periods=n).astype(str)
})

# 1. Kotorkan Data: Kasih NaN
data.loc[np.random.choice(n, 10, replace=False), 'umur'] = np.nan
data.loc[np.random.choice(n, 8, replace=False), 'total_belanja'] = np.nan

# 2. Kotorkan Data: Kasih Duplikat 5 baris
data = pd.concat([data, data.sample(5)], ignore_index=True)

# 3. Kotorkan Data: Tipe data & format aneh
data['total_belanja'] = data['total_belanja'].apply(lambda x: f"Rp{x:,.0f}".replace(',', '.') if pd.notna(x) else x)
data.loc[3, 'umur'] = 199 # Outlier
data.loc[7, 'total_belanja'] = 'Rp-50.000' # Outlier negatif

# 4. Simpan Jadi CSV
data.to_csv('data_penjualan_kotor.csv', index=False)
print("Dataset 100+ baris wes dadi: data_penjualan_kotor.csv")
print(data.head())

Dataset 100+ baris wes dadi: data_penjualan_kotor.csv
   id_transaksi   nama   umur       kota jenis_pembayaran total_belanja  \
0             1   Doni   45.0  Surabaya              CASH   Rp1.129.600
1             2    Eka   24.0  Surabaya          Transfer   Rp1.075.715
2             3  Citra   26.0        sby             CASH   Rp1.168.889
3             4    Eka  199.0    Jakarta         Transfer   Rp1.488.533
4             5    Eka   29.0        jkt             CASH     Rp234.078

      tanggal
0  2025-09-01
1  2025-09-02
2  2025-09-03
3  2025-09-04
4  2025-09-05

In [3]:
data=pd.read_csv('data_penjualan_kotor.csv')
data

,id_transaksi,nama,umur,kota,jenis_pembayaran,total_belanja,tanggal
0,1,Doni,45.0,Surabaya,CASH,Rp1.129.600,2025-09-01
1,2,Eka,24.0,Surabaya,Transfer,Rp1.075.715,2025-09-02
2,3,Citra,26.0,sby,CASH,Rp1.168.889,2025-09-03
3,4,Eka,199.0,Jakarta,Transfer,Rp1.488.533,2025-09-04
4,5,Eka,29.0,jkt,CASH,Rp234.078,2025-09-05
...,...,...,...,...,...,...,...
100,62,Doni,NaN,sby,QRIS,Rp688.836,2025-11-01
101,15,Doni,NaN,jkt,QRIS,Rp1.710.099,2025-09-15
102,40,Ani,56.0,sby,transfer,Rp1.648.809,2025-10-10
103,78,Doni,41.0,sby,transfer,Rp194.356,2025-11-17
104,94,Citra,36.0,Surabaya,QRIS,Rp826.665,2025-12-03

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105 entries, 0 to 104
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_transaksi      105 non-null    int64
 1   nama              105 non-null    object
 2   umur              93 non-null     float64
 3   kota              105 non-null    object
 4   jenis_pembayaran  105 non-null    object
 5   total_belanja     97 non-null     object
 6   tanggal           105 non-null    object
dtypes: float64(1), int64(1), object(5)
memory usage: 5.9+ KB

In [5]:
data.describe(include='all')

,id_transaksi,nama,umur,kota,jenis_pembayaran,total_belanja,tanggal
count,105.000000,105,93.000000,105,105,97,105
unique,NaN,5,NaN,5,4,92,100
top,NaN,Doni,NaN,sby,CASH,Rp1.710.099,2025-09-15
freq,NaN,29,NaN,29,31,2,2
mean,50.847619,NaN,41.215054,NaN,NaN,NaN,NaN
std,28.999927,NaN,21.000440,NaN,NaN,NaN,NaN
min,1.000000,NaN,18.000000,NaN,NaN,NaN,NaN
25%,26.000000,NaN,29.000000,NaN,NaN,NaN,NaN
50%,51.000000,NaN,43.000000,NaN,NaN,NaN,NaN
75%,76.000000,NaN,50.000000,NaN,NaN,NaN,NaN
max,100.000000,NaN,199.000000,NaN,NaN,NaN,NaN

In [6]:
#Ubah Tipe data umur, total belanja, dan tanggal

#umur
data['umur']=data['umur'].astype('Int64')

#hilangkan Rp di total belanja
data['total_belanja'] = data['total_belanja'].astype(str)
data['total_belanja'] = data['total_belanja'].replace('nan', np.nan) # Convert string 'nan' back to np.nan

# Now, perform string replacements. Use regex=False for literal matching of '.' and ','.
data['total_belanja'] = data['total_belanja'].str.replace('Rp', '', regex=False)
data['total_belanja'] = data['total_belanja'].str.replace('.', '', regex=False)
data['total_belanja'] = data['total_belanja'].str.replace(',', '', regex=False)

#tanggal
# Convert 'tanggal' column to datetime objects
data['tanggal'] = pd.to_datetime(data['tanggal'])

In [7]:
data['total_belanja'] = pd.to_numeric(data['total_belanja'], errors='coerce')
data['total_belanja'] = data['total_belanja'].astype('Int64')

In [8]:
data

,id_transaksi,nama,umur,kota,jenis_pembayaran,total_belanja,tanggal
0,1,Doni,45,Surabaya,CASH,1129600,2025-09-01
1,2,Eka,24,Surabaya,Transfer,1075715,2025-09-02
2,3,Citra,26,sby,CASH,1168889,2025-09-03
3,4,Eka,199,Jakarta,Transfer,1488533,2025-09-04
4,5,Eka,29,jkt,CASH,234078,2025-09-05
...,...,...,...,...,...,...,...
100,62,Doni,<NA>,sby,QRIS,688836,2025-11-01
101,15,Doni,<NA>,jkt,QRIS,1710099,2025-09-15
102,40,Ani,56,sby,transfer,1648809,2025-10-10
103,78,Doni,41,sby,transfer,194356,2025-11-17
104,94,Citra,36,Surabaya,QRIS,826665,2025-12-03

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105 entries, 0 to 104
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_transaksi      105 non-null    int64
 1   nama              105 non-null    object
 2   umur              93 non-null     Int64
 3   kota              105 non-null    object
 4   jenis_pembayaran  105 non-null    object
 5   total_belanja     97 non-null     Int64
 6   tanggal           105 non-null    datetime64[ns]
dtypes: Int64(2), datetime64[ns](1), int64(1), object(3)
memory usage: 6.1+ KB

In [10]:
jenis_pembayaran = data['jenis_pembayaran'].unique()
jenis_pembayaran

array(['CASH', 'Transfer', 'QRIS', 'transfer'], dtype=object)

In [11]:
#seragamkan huruf pada kolom jenis pembayaran
data['jenis_pembayaran']=data['jenis_pembayaran'].str.lower().str.strip().str.title()

In [12]:
data['jenis_pembayaran'].unique()

array(['Cash', 'Transfer', 'Qris'], dtype=object)

In [13]:
kota = data['kota'].unique()
kota

array(['Surabaya ', 'sby', 'Jakarta', 'jkt', ' SBY'], dtype=object)

In [14]:
data['kota']=data['kota'].str.lower().str.strip()

kamus_kota={
   'sby':'Surabaya',
    'surabaya':'Surabaya',
   'jakarta':'Jakarta',
   'jkt':'Jakarta'
}

data['kota']=data['kota'].replace(kamus_kota)

In [15]:
data['kota'].unique()

array(['Surabaya', 'Jakarta'], dtype=object)

In [16]:
data

,id_transaksi,nama,umur,kota,jenis_pembayaran,total_belanja,tanggal
0,1,Doni,45,Surabaya,Cash,1129600,2025-09-01
1,2,Eka,24,Surabaya,Transfer,1075715,2025-09-02
2,3,Citra,26,Surabaya,Cash,1168889,2025-09-03
3,4,Eka,199,Jakarta,Transfer,1488533,2025-09-04
4,5,Eka,29,Jakarta,Cash,234078,2025-09-05
...,...,...,...,...,...,...,...
100,62,Doni,<NA>,Surabaya,Qris,688836,2025-11-01
101,15,Doni,<NA>,Jakarta,Qris,1710099,2025-09-15
102,40,Ani,56,Surabaya,Transfer,1648809,2025-10-10
103,78,Doni,41,Surabaya,Transfer,194356,2025-11-17
104,94,Citra,36,Surabaya,Qris,826665,2025-12-03

In [17]:
nama=data['nama'].unique()
nama

array(['Doni', 'Eka', 'Citra', 'Ani', 'Budi'], dtype=object)

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105 entries, 0 to 104
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_transaksi      105 non-null    int64
 1   nama              105 non-null    object
 2   umur              93 non-null     Int64
 3   kota              105 non-null    object
 4   jenis_pembayaran  105 non-null    object
 5   total_belanja     97 non-null     Int64
 6   tanggal           105 non-null    datetime64[ns]
dtypes: Int64(2), datetime64[ns](1), int64(1), object(3)
memory usage: 6.1+ KB

In [19]:
data.isnull().sum()

id_transaksi         0
nama                 0
umur                12
kota                 0
jenis_pembayaran     0
total_belanja        8
tanggal              0
dtype: int64

In [20]:
#Handle Missing Data umur dan total belanja

#umur diisi median
data['umur']=data['umur'].fillna(data['umur'].median())

#total belanja bolong diisi 0
data['total_belanja']=data['total_belanja'].fillna(0)

In [21]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105 entries, 0 to 104
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_transaksi      105 non-null    int64
 1   nama              105 non-null    object
 2   umur              105 non-null    Int64
 3   kota              105 non-null    object
 4   jenis_pembayaran  105 non-null    object
 5   total_belanja     105 non-null    Int64
 6   tanggal           105 non-null    datetime64[ns]
dtypes: Int64(2), datetime64[ns](1), int64(1), object(3)
memory usage: 6.1+ KB

In [22]:
#Cek Data Duplikat

data.duplicated().sum()

np.int64(5)

In [23]:
#Hilangkan Data Duplikat

data=data.drop_duplicates()
data

,id_transaksi,nama,umur,kota,jenis_pembayaran,total_belanja,tanggal
0,1,Doni,45,Surabaya,Cash,1129600,2025-09-01
1,2,Eka,24,Surabaya,Transfer,1075715,2025-09-02
2,3,Citra,26,Surabaya,Cash,1168889,2025-09-03
3,4,Eka,199,Jakarta,Transfer,1488533,2025-09-04
4,5,Eka,29,Jakarta,Cash,234078,2025-09-05
...,...,...,...,...,...,...,...
95,96,Citra,43,Surabaya,Transfer,1219748,2025-12-05
96,97,Eka,49,Surabaya,Cash,1455478,2025-12-06
97,98,Ani,23,Surabaya,Cash,0,2025-12-07
98,99,Ani,49,Jakarta,Cash,1554544,2025-12-08
99,100,Budi,21,Jakarta,Cash,1417293,2025-12-09

In [28]:
# Hilangkan outlier umur yang tidak masuk akal (misalnya umur > 100 tahun)
data = data[data['umur'] <= 100]
data_final = data.copy()
data_final.head()

,id_transaksi,nama,umur,kota,jenis_pembayaran,total_belanja,tanggal
0,1,Doni,45,Surabaya,Cash,1129600,2025-09-01
1,2,Eka,24,Surabaya,Transfer,1075715,2025-09-02
2,3,Citra,26,Surabaya,Cash,1168889,2025-09-03
4,5,Eka,29,Jakarta,Cash,234078,2025-09-05
5,6,Ani,43,Surabaya,Qris,1456005,2025-09-06

In [29]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 99 entries, 0 to 99
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_transaksi      99 non-null     int64
 1   nama              99 non-null     object
 2   umur              99 non-null     Int64
 3   kota              99 non-null     object
 4   jenis_pembayaran  99 non-null     object
 5   total_belanja     99 non-null     Int64
 6   tanggal           99 non-null     datetime64[ns]
dtypes: Int64(2), datetime64[ns](1), int64(1), object(3)
memory usage: 6.4+ KB

In [30]:
data_final=data.copy()
data_final

,id_transaksi,nama,umur,kota,jenis_pembayaran,total_belanja,tanggal
0,1,Doni,45,Surabaya,Cash,1129600,2025-09-01
1,2,Eka,24,Surabaya,Transfer,1075715,2025-09-02
2,3,Citra,26,Surabaya,Cash,1168889,2025-09-03
4,5,Eka,29,Jakarta,Cash,234078,2025-09-05
5,6,Ani,43,Surabaya,Qris,1456005,2025-09-06
...,...,...,...,...,...,...,...
95,96,Citra,43,Surabaya,Transfer,1219748,2025-12-05
96,97,Eka,49,Surabaya,Cash,1455478,2025-12-06
97,98,Ani,23,Surabaya,Cash,0,2025-12-07
98,99,Ani,49,Jakarta,Cash,1554544,2025-12-08
99,100,Budi,21,Jakarta,Cash,1417293,2025-12-09

In [31]:
data_final

,id_transaksi,nama,umur,kota,jenis_pembayaran,total_belanja,tanggal
0,1,Doni,45,Surabaya,Cash,1129600,2025-09-01
1,2,Eka,24,Surabaya,Transfer,1075715,2025-09-02
2,3,Citra,26,Surabaya,Cash,1168889,2025-09-03
4,5,Eka,29,Jakarta,Cash,234078,2025-09-05
5,6,Ani,43,Surabaya,Qris,1456005,2025-09-06
...,...,...,...,...,...,...,...
95,96,Citra,43,Surabaya,Transfer,1219748,2025-12-05
96,97,Eka,49,Surabaya,Cash,1455478,2025-12-06
97,98,Ani,23,Surabaya,Cash,0,2025-12-07
98,99,Ani,49,Jakarta,Cash,1554544,2025-12-08
99,100,Budi,21,Jakarta,Cash,1417293,2025-12-09